Filling the description for the 3rd section
ParticularLabs/EndToEndReliability pull request #3
Opened 2018-06-12 09:21 UTC by WojcikMike

2018-06-12 09:25 UTC, SzymonPobiega commented on README.md
> +Most of the exceptions  will be visible on the client side, and should be caught and logged. ???
Not sure I understand?

2018-06-12 09:46 UTC, WojcikMike commented on README.md
> +Most of the exceptions  will be visible on the client side, and should be caught and logged. ???
I am not sure what to put here beyond the sentence that I wrote

2018-06-12 15:23 UTC, kbaley commented on README.md
> +Most of the exceptions  will be visible on the client side, and should be caught and logged. ???
Do you mean client-side exceptions should be logged on the server? Or server-side exceptions should be displayed on the client?

2018-06-13 06:59 UTC, andreasohlund requested changes

2018-06-13 06:59 UTC, andreasohlund commented on README.md
> +Looking at the web server logs to look failures related to http requests that were doing updates. Any 4xx or 5xx errors related to PUT, POST, DELETE requests indicate that probably such issue occurre
>Looking at the web server logs to look failures related to http requests that were doing updates

How about

Monitoring web server logs for failures related to http requests modifying data

2018-06-13 06:59 UTC, andreasohlund commented on README.md
> +Most of the exceptions  will be visible on the client side, and should be caught and logged. ???
Isn't this the continuation of the first sentence, ie not all errors will be in the server logs so to have "full coverage" you need to catch http releated errors in the client as well?

So perhaps remove this and extend the first sentence?

2018-06-13 06:59 UTC, andreasohlund commented on README.md
> +The same issue exists in integration scenarios when a client is not owned by you, and simply calling http api.
... which makes it more complex given that you don't own the client?

2018-06-14 07:51 UTC, andreasohlund approved these changes

2018-06-14 07:51 UTC, andreasohlund commented
@SzymonPobiega can you take a quick glance and merge?

2018-06-14 08:28 UTC, SzymonPobiega approved these changes

2018-06-14 08:28 UTC, merged